dateModified: 1595863690
email:
  fromEmail: webdev@nixondesign.com
  fromName: Craft
  template: null
  transportSettings: null
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  059578ee-ad91-4430-b467-c870d8cf1579:
    name: Common
  fb69239b-76a5-43f2-b59f-0adffcac83e7:
    name: SEO
fields:
  7867a02a-c8b9-4136-8ffe-fcece191ca3c:
    contentColumnType: string
    fieldGroup: 059578ee-ad91-4430-b467-c870d8cf1579
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_body}}'
      localizeBlocks: false
      maxBlocks: ''
      minBlocks: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  8cfd9379-c00e-49e6-88c5-e5394a3eaf7c:
    contentColumnType: text
    fieldGroup: fb69239b-76a5-43f2-b59f-0adffcac83e7
    handle: metaTitle
    instructions: ''
    name: 'Meta Title'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9435729b-0cbb-4d4c-bc3d-1abd51e3892e:
    contentColumnType: text
    fieldGroup: 059578ee-ad91-4430-b467-c870d8cf1579
    handle: alt
    instructions: ''
    name: 'Alt Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eabfed67-715e-4222-9e32-9bd51ac22471:
    contentColumnType: text
    fieldGroup: fb69239b-76a5-43f2-b59f-0adffcac83e7
    handle: metaDescription
    instructions: ''
    name: 'Meta Description'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
matrixBlockTypes:
  8b71776a-54bd-43e6-a5f1-9f6e2c5c516b:
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      d04d55c2-baff-4088-b0e7-a2f6f64e3c93:
        tabs:
          -
            fields:
              7587301a-42cc-4897-a382-de451d6a474c:
                required: true
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      7587301a-42cc-4897-a382-de451d6a474c:
        contentColumnType: string
        fieldGroup: null
        handle: image
        instructions: ''
        name: Image
        searchable: true
        settings:
          allowedKinds:
            - image
          defaultUploadLocationSource: 'volume:795e072f-98ce-4a14-ae63-4e3a4e5142ca'
          defaultUploadLocationSubpath: ''
          limit: '1'
          localizeRelations: false
          restrictFiles: '1'
          selectionLabel: 'Add an image'
          singleUploadLocationSource: 'volume:795e072f-98ce-4a14-ae63-4e3a4e5142ca'
          singleUploadLocationSubpath: ''
          source: null
          sources:
            - 'volume:9e21bfc8-59c7-4a1e-9695-b710f984ea53'
          targetSiteId: null
          useSingleFolder: ''
          viewMode: large
        translationKeyFormat: null
        translationMethod: site
        type: craft\fields\Assets
    handle: image
    name: Image
    sortOrder: 4
  aa2eaa16-dc8a-46f9-a82f-fc5d7a460eb8:
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      1b052929-8c4b-4400-b778-4ee14a43782f:
        tabs:
          -
            fields:
              171d8286-303a-4222-8f11-664c1dd49891:
                required: true
                sortOrder: 2
              761cac28-e032-467b-96ed-b3a0d1b17c2f:
                required: true
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      171d8286-303a-4222-8f11-664c1dd49891:
        contentColumnType: text
        fieldGroup: null
        handle: heading
        instructions: ''
        name: Heading
        searchable: true
        settings:
          charLimit: ''
          code: ''
          columnType: text
          initialRows: '4'
          multiline: ''
          placeholder: ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\PlainText
      761cac28-e032-467b-96ed-b3a0d1b17c2f:
        contentColumnType: string
        fieldGroup: null
        handle: hx
        instructions: ''
        name: Level
        searchable: true
        settings:
          options:
            -
              __assoc__:
                -
                  - label
                  - One
                -
                  - value
                  - '1'
                -
                  - default
                  - '1'
            -
              __assoc__:
                -
                  - label
                  - Two
                -
                  - value
                  - '2'
                -
                  - default
                  - ''
            -
              __assoc__:
                -
                  - label
                  - Three
                -
                  - value
                  - '3'
                -
                  - default
                  - ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\Dropdown
    handle: heading
    name: Heading
    sortOrder: 1
  b8cc71a5-3887-4789-a31a-c9b7b7960631:
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      cb92abef-facf-4b86-8521-8ef1ffd73466:
        tabs:
          -
            fields:
              e6a60e1a-23f0-4d30-b809-561e56330f27:
                required: true
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      e6a60e1a-23f0-4d30-b809-561e56330f27:
        contentColumnType: text
        fieldGroup: null
        handle: text
        instructions: ''
        name: Text
        searchable: true
        settings:
          availableTransforms: '*'
          availableVolumes: '*'
          columnType: text
          purifierConfig: ''
          purifyHtml: '1'
          redactorConfig: Standard.json
          removeEmptyTags: '1'
          removeInlineStyles: '1'
          removeNbsp: '1'
        translationKeyFormat: null
        translationMethod: none
        type: craft\redactor\Field
    handle: text
    name: Text
    sortOrder: 2
  bf649cdd-30ce-490d-aef0-493c9bb4651b:
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      b00bc0a1-a48e-42d0-9638-f08dc9c9727a:
        tabs:
          -
            fields:
              0e5225da-6c68-42ca-bde8-3a2247219969:
                required: true
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      0e5225da-6c68-42ca-bde8-3a2247219969:
        contentColumnType: text
        fieldGroup: null
        handle: quote
        instructions: ''
        name: Quote
        searchable: true
        settings:
          charLimit: ''
          code: ''
          columnType: text
          initialRows: '2'
          multiline: '1'
          placeholder: ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\PlainText
    handle: blockquote
    name: Blockquote
    sortOrder: 3
plugins:
  assetrev:
    enabled: true
    schemaVersion: 1.0.0
  cookies:
    enabled: true
    schemaVersion: 1.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    enabled: true
    schemaVersion: 2.3.0
sections:
  9dc3c5ac-0e8f-4d8e-a51c-a7ac78891c7f:
    enableVersioning: false
    entryTypes:
      4a8d5656-d418-4987-99e9-5219c2d65824:
        handle: pageNotFound
        hasTitleField: false
        name: 'Page Not Found'
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: ''
    handle: pageNotFound
    name: 'Page Not Found'
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      29077885-d696-4ee7-9a99-ea42e8f64311:
        enabledByDefault: true
        hasUrls: true
        template: '404'
        uriFormat: '404'
    type: single
  de7026b1-fc54-49fa-93ab-9759b3c72110:
    enableVersioning: false
    entryTypes:
      e11afaf6-11f4-4cb1-944a-ee397b8d8270:
        handle: homepage
        hasTitleField: false
        name: Homepage
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: ''
    handle: homepage
    name: Homepage
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      29077885-d696-4ee7-9a99-ea42e8f64311:
        enabledByDefault: true
        hasUrls: true
        template: index
        uriFormat: __home__
    type: single
siteGroups:
  e70939fb-8b55-4880-b361-6437b2756120:
    name: Craft
sites:
  29077885-d696-4ee7-9a99-ea42e8f64311:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-GB
    name: Craft
    primary: true
    siteGroup: e70939fb-8b55-4880-b361-6437b2756120
    sortOrder: 1
system:
  edition: pro
  live: true
  name: Craft
  schemaVersion: 3.4.11
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: ''
  photoSubpath: 'photos/{username}'
  photoVolumeUid: e0216f7b-97d4-48e5-905f-b8bba4979a29
  requireEmailVerification: true
volumes:
  795e072f-98ce-4a14-ae63-4e3a4e5142ca:
    handle: documents
    hasUrls: true
    name: Documents
    settings:
      path: '@webroot/uploads/documents'
    sortOrder: 1
    type: craft\volumes\Local
    url: '@web/uploads/documents'
  9e21bfc8-59c7-4a1e-9695-b710f984ea53:
    fieldLayouts:
      00b9e43e-fb66-49f3-a719-d0e2bfe38334:
        tabs:
          -
            fields:
              9435729b-0cbb-4d4c-bc3d-1abd51e3892e:
                required: false
                sortOrder: 1
            name: Content
            sortOrder: 1
    handle: images
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    sortOrder: 2
    type: craft\volumes\Local
    url: '@web/uploads/images'
  e0216f7b-97d4-48e5-905f-b8bba4979a29:
    handle: users
    hasUrls: false
    name: Users
    settings:
      path: '@webroot/uploads/users'
    sortOrder: 3
    type: craft\volumes\Local
    url: ''
